In [3]:
#Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

#Importing selenium webdriver
from selenium import webdriver

#Importing required Exceptions
from selenium.common.exceptions import StaleElementReferenceException,NoSuchElementException

#Importing requests
import requests

#importing regx
import re
from selenium.webdriver.common.by import By

In [35]:
#Q1.

In [36]:
# Connect to webdriver
driver = webdriver.Chrome(r'C:\Users\COTMAC\Downloads\chromedriver_win32\chromedriver.exe')

C:\Users\COTMAC\AppData\Local\Temp/ipykernel_1396/2295598310.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r'C:\Users\COTMAC\Downloads\chromedriver_win32\chromedriver.exe')

In [37]:
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')

In [38]:
Youtube_Rank=[]
Youtube_Name=[]
Youtube_Artist=[]
Youtube_Upload_Date=[]
Youtube_Views=[]



#Name_tags=driver.find_elements(By.CLASS_NAME,'mw-redirect')
#Name_tags=driver.find_elements(By.XPATH,"//a[@class='mw-redirect']")
Rank_tags=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]//tbody//tr//td[1]')
for i in Rank_tags[0:30]:
    time.sleep(5)
    try:
        Youtube_Rank.append(i.text)
    except NoSuchElementException :
        Youtube_Rank.append('Not present')

Name_tags=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]//tbody//tr//td[2]')
for i in Name_tags[0:30]:
    time.sleep(5)
    try:
        Youtube_Name.append(i.text)
    except NoSuchElementException :
        Youtube_Name.append('Not present')
        
Artist_tags=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]//tbody//tr//td[3]')
for i in Artist_tags[0:30]:
    time.sleep(5)
    try:
        Youtube_Artist.append(i.text)
    except NoSuchElementException :
        Youtube_Artist.append('Not present')
        
Upload_Date_tags=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]//tbody//tr//td[5]')
for i in Upload_Date_tags[0:30]:
    time.sleep(5)
    try:
        Youtube_Upload_Date.append(i.text)
    except NoSuchElementException :
        Youtube_Upload_Date.append('Not present')
        
Name_Views=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]//tbody//tr//td[4]')
for i in Name_Views[0:30]:
    time.sleep(5)
    try:
        Youtube_Views.append(i.text)
    except NoSuchElementException :
        Youtube_Views.append('Not present')

In [39]:
print(len(Youtube_Rank),len(Youtube_Name),len(Youtube_Artist),len(Youtube_Upload_Date),len(Youtube_Views))

30 30 30 30 30

In [40]:
df=pd.DataFrame({'Youtube_Rank':Youtube_Rank,'Youtube_Name':Youtube_Name,'Youtube_Artist':Youtube_Artist,'Youtube_Upload_Date':Youtube_Upload_Date,'Youtube_Views':Youtube_Views})
df

,Youtube_Rank,Youtube_Name,Youtube_Artist,Youtube_Upload_Date,Youtube_Views
0,1.,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",11.05
1,2.,"""Despacito""[6]",Luis Fonsi,"January 12, 2017",7.93
2,3.,"""Johny Johny Yes Papa""[12]",LooLoo Kids,"October 8, 2016",6.40
3,4.,"""Shape of You""[13]",Ed Sheeran,"January 30, 2017",5.77
4,5.,"""See You Again""[15]",Wiz Khalifa,"April 6, 2015",5.59
5,6.,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,"May 2, 2018",5.54
6,7.,"""Phonics Song with Two Words""[21]",ChuChu TV,"March 6, 2014",4.77
7,8.,"""Uptown Funk""[22]",Mark Ronson,"November 19, 2014",4.65
8,9.,"""Learning Colors – Colorful Eggs on a Farm""[23]",Miroshka TV,"February 27, 2018",4.60
9,10.,"""Masha and the Bear – Recipe for Disaster""[24]",Get Movies,"January 31, 2012",4.50
10,11.,"""Gangnam Style""[25]",Psy,"July 15, 2012",4.50
11,12.,"""Wheels on the Bus""[30]",Cocomelon – Nursery Rhymes,"May 24, 2018",4.24
12,13.,"""Dame Tu Cosita""[31]",El Chombo,"April 5, 2018",4.00
13,14.,"""Sugar""[32]",Maroon 5,"January 14, 2015",3.74
14,15.,"""Roar""[33]",Katy Perry,"September 5, 2013",3.63
15,16.,"""Counting Stars""[34]",OneRepublic,"May 31, 2013",3.62
16,17.,"""Sorry""[35]",Justin Bieber,"October 22, 2015",3.57
17,18.,"""Thinking Out Loud""[36]",Ed Sheeran,"October 7, 2014",3.48
18,19.,"""Axel F""[37]",Crazy Frog,"June 16, 2009",3.45
19,20.,"""Dark Horse""[38]",Katy Perry,"February 20, 2014",3.32
20,21.,"""Girls Like You""[39]",Maroon 5,"May 31, 2018",3.32
21,22.,"""Faded""[40]",Alan Walker,"December 3, 2015",3.32
22,23.,"""Baa Baa Black Sheep""[41]",Cocomelon – Nursery Rhymes,"June 25, 2018",3.31
23,24.,"""Let Her Go""[42]",Passenger,"July 25, 2012",3.27
24,25.,"""Bailando""[43]",Enrique Iglesias,"April 11, 2014",3.25
25,26.,"""Lean On""[44]",Major Lazer,"March 22, 2015",3.24
26,27.,"""Perfect""[45]",Ed Sheeran,"November 9, 2017",3.22
27,28.,"""Waka Waka (This Time for Africa)""[46]",Shakira,"June 4, 2010",3.21
28,29.,"""Shake It Off""[47]",Taylor Swift,"August 18, 2014",3.19
29,30.,"""Mi Gente""[48]",J Balvin,"June 29, 2017",3.11

In [ ]:
#Q2.

In [41]:
# Connect to webdriver
driver = webdriver.Chrome(r'C:\Users\COTMAC\Downloads\chromedriver_win32\chromedriver.exe')

C:\Users\COTMAC\AppData\Local\Temp/ipykernel_1396/2295598310.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r'C:\Users\COTMAC\Downloads\chromedriver_win32\chromedriver.exe')

In [42]:
driver.get('https://www.bcci.tv/')

In [43]:
pop_up=driver.find_element(By.XPATH,"/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a")
pop_up.click()

In [49]:
BCCI_Title=[]
BCCI_Series=[]
BCCI_Place=[]
BCCI_Date=[]
BCCI_Time=[]

Title_tags=driver.find_elements(By.XPATH,"//span[@class='matchOrderText ng-binding ng-scope']")
for i in Title_tags:
    time.sleep(5)
    try:
        BCCI_Title.append(i.text)
    except NoSuchElementException :
        BCCI_Title.append('Not present')
        
#Series_tags=driver.find_elements(By.XPATH,"//h5[@class='fix-text']")
Series_tags=driver.find_elements(By.XPATH,'//div[@class="fixture-card-top"]')
for i in Series_tags:
    time.sleep(5)
    try:
        BCCI_Series.append(i.text.split('\n')[0])
    except NoSuchElementException :
        BCCI_Series.append('Not present')
        
Place_tags=driver.find_elements(By.XPATH,"//div[@class='fixture-card-bottom']")
for i in Place_tags:
    time.sleep(5)
    try:
        BCCI_Place.append(i.text.split('-')[1])
    except NoSuchElementException :
        BCCI_Place.append('Not present')

BCCI_Date_tags=driver.find_elements(By.XPATH,'//div[@class="fixture-card-top"]')
for i in BCCI_Date_tags:
    time.sleep(5)
    try:
        BCCI_Date.append(i.text.split('\n')[1])
    except NoSuchElementException :
        BCCI_Date.append('Not present')
        
Time_tags=driver.find_elements(By.XPATH,'//div[@class="fixture-card-top"]')
for i in Time_tags:
    time.sleep(5)
    try:
        BCCI_Time.append(i.text.split('\n')[2])
    except NoSuchElementException :
        BCCI_Time.append('Not present')

In [50]:
print(len(BCCI_Title),len(BCCI_Series),len(BCCI_Place),len(BCCI_Date),len(BCCI_Time))

5 5 5 5 5

In [51]:
df=pd.DataFrame({'BCCI_Title':BCCI_Title,'BCCI_Series':BCCI_Series,'BCCI_Place':BCCI_Place,'BCCI_Date':BCCI_Date,'BCCI_Time':BCCI_Time})
df

,BCCI_Title,BCCI_Series,BCCI_Place,BCCI_Date,BCCI_Time
0,1st ODI -,INDIA TOUR OF ZIMBABWE ODI SERIES 2022,"Harare Sports Club, Harare\nMatch Centre",18 AUG 2022,10:15 AM AST
1,2nd ODI -,INDIA TOUR OF ZIMBABWE ODI SERIES 2022,"Harare Sports Club, Harare\nMatch Centre",20 AUG 2022,10:15 AM AST
2,3rd ODI -,INDIA TOUR OF ZIMBABWE ODI SERIES 2022,"Harare Sports Club, Harare\nMatch Centre",22 AUG 2022,10:15 AM AST
3,1st T20I -,ASIA CUP 2022,"Dubai International Cricket Stadium, Dubai\nM...",28 AUG 2022,5:00 PM AST
4,2nd T20I -,ASIA CUP 2022,"Dubai International Cricket Stadium, Dubai\nM...",31 AUG 2022,5:00 PM AST

In [ ]:
#Q3.

In [52]:
# Connect to webdriver
driver = webdriver.Chrome(r'C:\Users\COTMAC\Downloads\chromedriver_win32\chromedriver.exe')

C:\Users\COTMAC\AppData\Local\Temp/ipykernel_1396/2295598310.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r'C:\Users\COTMAC\Downloads\chromedriver_win32\chromedriver.exe')

In [53]:
driver.get('https://www.guru99.com/')

In [55]:
search1=driver.find_element(By.XPATH,'//input[@class="gsc-input"]')
search1.send_keys('selenium exception handling')

pop_up1=driver.find_element(By.XPATH,"//button[@class='gsc-search-button gsc-search-button-v2']")
pop_up1.click()

In [56]:
Exception_Name=[]
Exception_Desc=[]


Exception_Name_tags=driver.find_elements(By.XPATH,"//div[@class='gs-title']")
for i in Exception_Name_tags:
    time.sleep(5)
    try:
        Exception_Name.append(i.text)
    except NoSuchElementException :
        Exception_Name.append('Not present')

Exception_Desc_tags=driver.find_elements(By.XPATH,"//div[@class='gs-bidi-start-align gs-snippet']")
for i in Exception_Desc_tags:
    time.sleep(5)
    try:
        Exception_Desc.append(i.text)
    except NoSuchElementException :
        Exception_Desc.append('Not present')

In [57]:
print(len(Exception_Name),len(Exception_Desc))

11 11

In [58]:
df=pd.DataFrame({'Exception_Name':Exception_Name,'Exception_Desc':Exception_Desc})
df

,Exception_Name,Exception_Desc
0,Selenium Exception Handling (Common Exceptions...,"Dhuʻl-H. 24, 1443 AH ... Common Exceptions in ..."
1,How to Handle SSL Certificate in Selenium WebD...,"Dhuʻl-Q. 26, 1443 AH ... For handling SSL cert..."
2,Try Catch in Java: Exception Handling Example,"Dhuʻl-H. 10, 1443 AH ... All these errors are ..."
3,"Python Exception Handling: try, catch, finally...","Dhuʻl-H. 10, 1443 AH ... In this Python except..."
4,"C++ Exception Handling: Try, Catch, throw Example","Dhuʻl-H. 10, 1443 AH ... Next, the exception h..."
5,Oracle PL/SQL Exception Handling: Examples to ...,"Dhuʻl-H. 3, 1443 AH ... Exception-Handling Syn..."
6,Exception Handling in VB.Net: Try & Catch Hand...,"Dhuʻl-H. 22, 1443 AH ... In this VB.Net Except..."
7,PHP Try Catch Example: Exception & Error Handl...,"Dhuʻl-H. 27, 1443 AH ... Learn with example Ex..."
8,JSP Exception Handling: Error Page in JSP,"Dhuʻl-H. 24, 1443 AH ... In this tutorial, we ..."
9,"Asp.Net Page Level Tracing, Debugging, Error H...","Dhuʻl-Q. 26, 1443 AH ... In any application, e..."
10,,

In [17]:
#Q4.

In [95]:
# Connect to webdriver
driver = webdriver.Chrome(r'C:\Users\COTMAC\Downloads\chromedriver_win32\chromedriver.exe')

C:\Users\COTMAC\AppData\Local\Temp/ipykernel_1396/2295598310.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r'C:\Users\COTMAC\Downloads\chromedriver_win32\chromedriver.exe')

In [96]:
driver.get('http://statisticstimes.com/')

In [98]:

search1=driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/button')
search1.click()

pop_up1=driver.find_element(By.XPATH,"/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]")
pop_up1.click()

pop_up2=driver.find_element(By.XPATH,"/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")
pop_up2.click()

In [99]:
GDP_Rank=[]
GDP_State=[]


#GDP_Rank_tags=driver.find_elements(By.XPATH,"//table[@id='table_id']")

Rank_tags=driver.find_elements(By.XPATH,'//table[@class="display dataTable"]//tbody//tr//td[1]')
for i in Rank_tags:
    #time.sleep(5)
    try:
        GDP_Rank.append(i.text)
    except NoSuchElementException :
        GDP_Rank.append('Not present')
        
GDP_State_tags=driver.find_elements(By.XPATH,'//table[@class="display dataTable"]//tbody//tr//td[2]')
for i in GDP_State_tags:
    #time.sleep(5)
    try:
        GDP_State.append(i.text)
    except NoSuchElementException :
        GDP_State.append('Not present')

In [100]:
GDP_GSDP18=[]
GDP_GSDP17=[]
GDP_Share2017=[]

GDP_GSDP18_tags=driver.find_elements(By.XPATH,'//table[@class="display dataTable"]//tbody//tr//td[3]')
for i in GDP_GSDP18_tags:
    #time.sleep(5)
    try:
        GDP_GSDP18.append(i.text)
    except NoSuchElementException :
        GDP_GSDP18.append('Not present')
        
GDP_GSDP17_tags=driver.find_elements(By.XPATH,'//table[@class="display dataTable"]//tbody//tr//td[4]')
for i in GDP_GSDP17_tags:
    #time.sleep(5)
    try:
        GDP_GSDP17.append(i.text)
    except NoSuchElementException :
        GDP_GSDP17.append('Not present')
        
GDP_Share2017_tags=driver.find_elements(By.XPATH,'//table[@class="display dataTable"]//tbody//tr//td[5]')
for i in GDP_Share2017_tags:
    #time.sleep(5)
    try:
        GDP_Share2017.append(i.text)
    except NoSuchElementException :
        GDP_Share2017.append('Not present')

In [101]:
GDPBillian=[]
GDPCurrent1920=[]
GDPCurrent1819=[]


GDPBillian_tags=driver.find_elements(By.XPATH,'//table[@class="display dataTable"]//tbody//tr//td[6]')
for i in GDPBillian_tags:
    #time.sleep(5)
    try:
        GDPBillian.append(i.text)
    except NoSuchElementException :
        GDPBillian.append('Not present')
        
GDPCurrent1920_tags=driver.find_elements(By.XPATH,'//table[@class="display dataTable"]//tbody//tr//td[7]')
for i in GDPCurrent1920_tags:
    #time.sleep(5)
    try:
        GDPCurrent1920.append(i.text)
    except NoSuchElementException :
        GDPCurrent1920.append('Not present')
        
GDPCurrent1819_tags=driver.find_elements(By.XPATH,'//table[@class="display dataTable"]//tbody//tr//td[8]')
for i in GDPCurrent1819_tags:
    #time.sleep(5)
    try:
        GDPCurrent1819.append(i.text)
    except NoSuchElementException :
        GDPCurrent1819.append('Not present')

In [102]:
print(len(GDP_Rank),len(GDP_State),len(GDP_GSDP18),len(GDP_GSDP17),len(GDP_Share2017),len(GDPBillian),len(GDPCurrent1920),len(GDPCurrent1819))

66 66 66 66 66 66 66 33

In [109]:
df=pd.DataFrame({'GDP_Rank':GDP_Rank[0:33],'GDP_State':GDP_State[0:33],'GDP_GSDP18':GDP_GSDP18[0:33],'GDP_GSDP17':GDP_GSDP17[0:33],'GDP_Share2017':GDP_Share2017[0:33],'GDPBillian':GDPBillian[0:33],'GDPCurrent1920':GDPCurrent1920[0:33],'GDPCurrent1819':GDPCurrent1819[0:33]})
df

,GDP_Rank,GDP_State,GDP_GSDP18,GDP_GSDP17,GDP_Share2017,GDPBillian,GDPCurrent1920,GDPCurrent1819
0,1,Maharashtra,-,"2,632,792",13.94%,399.921,-,"2,039,074"
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629,"1,312,929","1,215,307"
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726,"1,166,817","1,123,982"
3,4,Gujarat,-,"1,502,899",7.96%,228.290,-,"1,186,379"
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806,"1,156,039","1,091,077"
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556,"793,223","739,525"
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179,"711,627","677,428"
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083,"672,018","621,301"
8,9,Telangana,"969,604","861,031",4.56%,130.791,"663,258","612,828"
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977,"561,801","522,009"
10,11,Kerala,-,"781,653",4.14%,118.733,-,"559,412"
11,12,Delhi,"856,112","774,870",4.10%,117.703,"634,408","590,569"
12,13,Haryana,"831,610","734,163",3.89%,111.519,"572,240","531,085"
13,14,Bihar,"611,804","530,363",2.81%,80.562,"414,977","375,651"
14,15,Punjab,"574,760","526,376",2.79%,79.957,"418,868","397,669"
15,16,Odisha,"521,275","487,805",2.58%,74.098,"396,499","376,877"
16,17,Assam,-,"315,881",1.67%,47.982,-,"234,048"
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187,"243,477","231,182"
18,19,Jharkhand,"328,598","297,204",1.57%,45.145,"240,036","224,986"
19,20,Uttarakhand,-,"245,895",1.30%,37.351,-,"193,273"
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690,-,"112,755"
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369,"124,403","117,851"
22,23,Goa,"80,449","73,170",0.39%,11.115,"63,408","57,787"
23,24,Tripura,"55,984","49,845",0.26%,7.571,"40,583","36,963"
24,25,Chandigarh,-,"42,114",0.22%,6.397,-,"31,192"
25,26,Puducherry,"38,253","34,433",0.18%,5.230,"25,093","23,013"
26,27,Meghalaya,"36,572","33,481",0.18%,5.086,"26,695","24,682"
27,28,Sikkim,"32,496","28,723",0.15%,4.363,"20,017","18,722"
28,29,Manipur,"31,790","27,870",0.15%,4.233,"20,673","19,300"
29,30,Nagaland,-,"27,283",0.14%,4.144,-,"17,647"
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737,-,"16,676"
31,32,Mizoram,"26,503","22,287",0.12%,3.385,"18,797","16,478"
32,33,Andaman & Nicobar Islands,-,-,-,-,-,-

In [110]:
#Q5.

In [110]:
# Connect to webdriver
driver = webdriver.Chrome(r'C:\Users\COTMAC\Downloads\chromedriver_win32\chromedriver.exe')

C:\Users\COTMAC\AppData\Local\Temp/ipykernel_11408/2295598310.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r'C:\Users\COTMAC\Downloads\chromedriver_win32\chromedriver.exe')

In [111]:
driver.get('https://github.com/')

In [112]:
search1=driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary')
search1.click()

pop_up1=driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a")
pop_up1.click()

In [113]:
#Q2.#fetching url to each job
Product_url=[]
start=0
end=1
for page in range(start,end):
    url=driver.find_elements(By.XPATH,'//p[@class="normal"]')
    for i in url:
        Product_url.append(i.get_attribute('href'))

In [142]:
Repository_Description=[]

for i in Product_url[0:25]:
    #driver.get(i)
    #time.sleep(5)
    try:
        Repository_Description_tags = driver.find_element(By.XPATH,'/html/body/div[4]/main/div[3]/div/div[2]/article[1]/p')
        Repository_Description.append(Repository_Description_tags.text)
    except NoSuchElementException :
            Repository_Description.append('Not present')

In [146]:
Repository_Title=[]
Repository_Contributors=[]
Repository_Language=[]

        
Repository_Title_tags=driver.find_elements(By.XPATH,"//h1[@class='h3 lh-condensed']")
for i in Repository_Title_tags:
    #time.sleep(5)
    try:
        Repository_Title.append(i.text)
    except NoSuchElementException :
        Repository_Title.append('Not present')

Repository_Contributors_tags=driver.find_elements(By.XPATH,"//div[@class='f6 color-fg-muted mt-2']")
for i in Repository_Contributors_tags:
    #time.sleep(5)
    try:
        Repository_Contributors.append(i.text)
    except NoSuchElementException :
        Repository_Contributors.append('Not present')
        
Repository_Language_tags=driver.find_elements(By.XPATH,"//span[@class='d-inline-block ml-0 mr-3']")
for i in Repository_Language_tags:
    #time.sleep(5)
    try:
        Repository_Language.append(i.text)
    except NoSuchElementException :
        Repository_Language.append('Not present')

In [148]:
len(Repository_Title),len(Repository_Description),len(Repository_Contributors)

(25, 25, 25)

In [149]:
df=pd.DataFrame({'Repository_Title':Repository_Title,'Repository_Description':Repository_Description,'Repository_Contributors':Repository_Contributors})
df

,Repository_Title,Repository_Description,Repository_Contributors
0,toeverything / AFFiNE,There can be more than Notion and Miro. Affine...,"TypeScript 4,574 168 Built by\n887 stars today"
1,jwasham / coding-interview-university,There can be more than Notion and Miro. Affine...,"228,597 61,477 Built by\n330 stars today"
2,iptv-org / iptv,There can be more than Notion and Miro. Affine...,"JavaScript 53,900 9,392 Built by\n259 stars today"
3,ventoy / Ventoy,There can be more than Notion and Miro. Affine...,"C 37,698 2,778 Built by\n178 stars today"
4,MarlinFirmware / Marlin,There can be more than Notion and Miro. Affine...,"C++ 13,570 17,024 Built by\n41 stars today"
5,Dreamacro / clash,There can be more than Notion and Miro. Affine...,"Go 29,794 4,120 Built by\n103 stars today"
6,arthurspk / guiadevbrasil,There can be more than Notion and Miro. Affine...,"7,674 1,028 Built by\n69 stars today"
7,donnemartin / system-design-primer,There can be more than Notion and Miro. Affine...,"Python 192,108 34,733 Built by\n188 stars today"
8,MatrixTM / MHDDoS,There can be more than Notion and Miro. Affine...,"Python 5,209 1,228 Built by\n197 stars today"
9,t3-oss / create-t3-app,There can be more than Notion and Miro. Affine...,"TypeScript 4,853 186 Built by\n158 stars today"
10,punk-security / dnsReaper,There can be more than Notion and Miro. Affine...,Python 414 35 Built by\n129 stars today
11,juliocesarfort / public-pentesting-reports,There can be more than Notion and Miro. Affine...,"CSS 6,069 1,533 Built by\n91 stars today"
12,facebookresearch / ParlAI,There can be more than Notion and Miro. Affine...,"Python 9,263 1,898 Built by\n87 stars today"
13,utmapp / UTM,There can be more than Notion and Miro. Affine...,"Swift 14,301 880 Built by\n139 stars today"
14,theboy181 / switch-ptchtxt-mods,There can be more than Notion and Miro. Affine...,170 30 Built by\n22 stars today
15,Asabeneh / 30-Days-Of-React,There can be more than Notion and Miro. Affine...,"JavaScript 15,178 3,887 Built by\n114 stars today"
16,github / docs,There can be more than Notion and Miro. Affine...,"JavaScript 10,851 56,265 Built by\n77 stars today"
17,josephmisiti / awesome-machine-learning,There can be more than Notion and Miro. Affine...,"Python 55,257 13,465 Built by\n110 stars today"
18,PKUFlyingPig / cs-self-learning,There can be more than Notion and Miro. Affine...,"HTML 11,520 1,606 Built by\n121 stars today"
19,jina-ai / discoart,There can be more than Notion and Miro. Affine...,"Python 2,116 107 Built by\n194 stars today"
20,trickest / cve,There can be more than Notion and Miro. Affine...,"HTML 3,423 407 Built by\n64 stars today"
21,HIT-UG-Group / DeepLearning-MuLi-Notes,There can be more than Notion and Miro. Affine...,"Jupyter Notebook 1,898 330 Built by\n68 stars ..."
22,hyprwm / Hyprland,There can be more than Notion and Miro. Affine...,"C++ 2,335 85 Built by\n93 stars today"
23,EbookFoundation / free-programming-books,There can be more than Notion and Miro. Affine...,"244,297 50,181 Built by\n242 stars today"
24,moyix / fauxpilot,There can be more than Notion and Miro. Affine...,"Python 4,122 110 Built by\n318 stars today"

In [3]:
#Q6.

In [87]:
# Connect to webdriver
driver = webdriver.Chrome(r'C:\Users\COTMAC\Downloads\chromedriver_win32\chromedriver.exe')

C:\Users\COTMAC\AppData\Local\Temp/ipykernel_11408/2295598310.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r'C:\Users\COTMAC\Downloads\chromedriver_win32\chromedriver.exe')

In [88]:
driver.get('https:/www.billboard.com/')

In [89]:
pop_up=driver.find_element(By.XPATH,"/html/body/div[3]/header/div[1]/div/div/div[2]/div/nav/ul/li[1]/a")
pop_up.click()
time.sleep(5)

In [90]:
search=driver.find_element(By.XPATH,"/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[1]/div[1]/div[2]/span/a")
search.click()

In [28]:
Song_Name=[]
Artist_Name=[]
Last_Week_Rank=[]
Peak_Rank=[]
Weeks_On_Board=[]

Song_Name_tags=driver.find_elements(By.XPATH,"//li[@class='o-chart-results-list__item // lrv-u-flex-grow-1 lrv-u-flex lrv-u-flex-direction-column lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light lrv-u-padding-l-050 lrv-u-padding-l-1@mobile-max']")
for i in Song_Name_tags:
#time.sleep(5)
    try:
        Song_Name.append(i.text.split('\n')[0])
    except NoSuchElementException :
        Song_Name.append('Not present')


Artist_Name_tags=driver.find_elements(By.XPATH,"//li[@class='o-chart-results-list__item // lrv-u-flex-grow-1 lrv-u-flex lrv-u-flex-direction-column lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light lrv-u-padding-l-050 lrv-u-padding-l-1@mobile-max']")
for i in Artist_Name_tags:
    #time.sleep(5)
    try:
        Artist_Name.append(i.text.split('\n')[1])
    except NoSuchElementException :
        Artist_Name.append('Not present')
        
Last_Week_Rank_tags=driver.find_elements(By.XPATH,"//li[@class='o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max']")
for i in Last_Week_Rank_tags[1:100]:
    #time.sleep(5)
    try:
        Last_Week_Rank.append(i.text.split(','))
    except NoSuchElementException :
        Last_Week_Rank.append('Not present')

Peak_Rank_tags=driver.find_elements(By.XPATH,"//li[@class='o-chart-results-list__item // a-chart-bg-color a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-background-color-grey-lightest lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-hidden@mobile-max']")
for i in Peak_Rank_tags[1:100]:
    #time.sleep(5)
    try:
        Peak_Rank.append(i.text.split(',')[0])
    except NoSuchElementException :
        Peak_Rank.append('Not present')

Weeks_On_Board_tags=driver.find_elements(By.XPATH,"//li[@class='o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max']")
for i in Weeks_On_Board_tags[1:100]:
    #time.sleep(5)
    try:
        Weeks_On_Board.append(i.text.split(',')[0])
    except NoSuchElementException :
        Weeks_On_Board.append('Not present')

In [29]:
print(len(Song_Name),len(Artist_Name),len(Last_Week_Rank),len(Weeks_On_Board),len(Peak_Rank))

99 99 99 99 99

In [30]:
df=pd.DataFrame({'Song_Name':Song_Name,'Artist_Name':Artist_Name,'Last_Week_Rank':Last_Week_Rank,'Peak_Rank':Peak_Rank,'Weeks_On_Board':Weeks_On_Board})
df

,Song_Name,Artist_Name,Last_Week_Rank,Peak_Rank,Weeks_On_Board
0,About Damn Time,Lizzo,[7],1,7
1,As It Was,Harry Styles,[1],,1
2,Running Up That Hill (A Deal With God),Kate Bush,[16],1,16
3,Wait For U,Future Featuring Drake & Tems,[2],,2
4,First Class,Jack Harlow,[18],1,18
...,...,...,...,...,...
94,Until I Found You,Stephen Sanchez,[39],3,39
95,Un Ratito,Bad Bunny,[40],,40
96,Best Thing Since Backroads,Jake Owen,[10],40,10
97,La Corriente,Bad Bunny & Tony Dize,[-],,-
98,"Bzrp Music Sessions, Vol. 52",Bizarrap & Quevedo,[1],50,1

In [103]:
Peak_Rank_tags=driver.find_elements(By.XPATH,"//li[@class='o-chart-results-list__item // a-chart-bg-color a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-background-color-grey-lightest lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-hidden@mobile-max']")
for i in Peak_Rank_tags[1:100]:
    #time.sleep(5)
    try:
        Peak_Rank.append(i.text.split(',')[0])
    except NoSuchElementException :
        Peak_Rank.append('Not present')

In [104]:
Peak_Rank

['1',
 '',
 '1',
 '',
 '1',
 '',
 '3',
 '',
 '1',
 '',
 '1',
 '',
 '7',
 '',
 '6',
 '',
 '9',
 '',
 '4',
 '',
 '9',
 '',
 '1',
 '',
 '13',
 '',
 '13',
 '',
 '9',
 '',
 '5',
 '',
 '1',
 '',
 '3',
 '',
 '19',
 '',
 '1',
 '',
 '6',
 '',
 '22',
 '',
 '23',
 '',
 '18',
 '',
 '25',
 '',
 '26',
 '',
 '27',
 '',
 '8',
 '',
 '5',
 '',
 '30',
 '',
 '20',
 '',
 '4',
 '',
 '4',
 '',
 '26',
 '',
 '28',
 '',
 '7',
 '',
 '14',
 '',
 '38',
 '',
 '6',
 '',
 '24',
 '',
 '41',
 '',
 '35',
 '',
 '43',
 '',
 '25',
 '',
 '30',
 '',
 '34',
 '',
 '47',
 '',
 '3',
 '',
 '40',
 '',
 '50',
 '1',
 '',
 '1',
 '',
 '1',
 '',
 '3',
 '',
 '1',
 '',
 '1',
 '',
 '7',
 '',
 '6',
 '',
 '9',
 '',
 '4',
 '',
 '9',
 '',
 '1',
 '',
 '13',
 '',
 '13',
 '',
 '9',
 '',
 '5',
 '',
 '1',
 '',
 '3',
 '',
 '19',
 '',
 '1',
 '',
 '6',
 '',
 '22',
 '',
 '23',
 '',
 '18',
 '',
 '25',
 '',
 '26',
 '',
 '27',
 '',
 '8',
 '',
 '5',
 '',
 '30',
 '',
 '20',
 '',
 '4',
 '',
 '4',
 '',
 '26',
 '',
 '28',
 '',
 '7',
 '',
 '14',
 '',
 '38',
 '',
 '6',
 '',
 '24',
 '',
 '41',
 '',
 '35',
 '',
 '43',
 '',
 '25',
 '',
 '30',
 '',
 '34',
 '',
 '47',
 '',
 '3',
 '',
 '40',
 '',
 '50',
 '1',
 '',
 '1',
 '',
 '1',
 '',
 '3',
 '',
 '1',
 '',
 '1',
 '',
 '7',
 '',
 '6',
 '',
 '9',
 '',
 '4',
 '',
 '9',
 '',
 '1',
 '',
 '13',
 '',
 '13',
 '',
 '9',
 '',
 '5',
 '',
 '1',
 '',
 '3',
 '',
 '19',
 '',
 '1',
 '',
 '6',
 '',
 '22',
 '',
 '23',
 '',
 '18',
 '',
 '25',
 '',
 '26',
 '',
 '27',
 '',
 '8',
 '',
 '5',
 '',
 '30',
 '',
 '20',
 '',
 '4',
 '',
 '4',
 '',
 '26',
 '',
 '28',
 '',
 '7',
 '',
 '14',
 '',
 '38',
 '',
 '6',
 '',
 '24',
 '',
 '41',
 '',
 '35',
 '',
 '43',
 '',
 '25',
 '',
 '30',
 '',
 '34',
 '',
 '47',
 '',
 '3',
 '',
 '40',
 '',
 '50']

In [4]:
#Q7.

In [5]:
# Connect to webdriver
driver = webdriver.Chrome(r'C:\Users\COTMAC\Downloads\chromedriver_win32\chromedriver.exe')

C:\Users\COTMAC\AppData\Local\Temp/ipykernel_18980/2295598310.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r'C:\Users\COTMAC\Downloads\chromedriver_win32\chromedriver.exe')

In [6]:
driver.get('https://www.naukri.com/hr-recruiters-consultants')

In [33]:
pop_up=driver.find_element(By.XPATH,"/html/body/div[1]/div/ul/li[2]/a/div")
pop_up.click()

search=driver.find_element(By.XPATH,"/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/div/div[1]/div[1]/div[2]/input")
search.click()

In [16]:
designation=driver.find_element(By.XPATH,"/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/div/div[1]/div[1]/div[2]/input")
designation.send_keys('Data science')

In [18]:
search1=driver.find_element(By.XPATH,"/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/button")
search1.click()

In [21]:
Name=[]
Designation=[]
Company=[]
Skills=[]
Location=[]


Name_tags=driver.find_elements(By.XPATH,"//span[@class='fl ellipsis']")
for i in Name_tags:
    #time.sleep(5)
    try:
        Name.append(i.text)
    except NoSuchElementException :
        Name.append('Not present')

Designation_tags=driver.find_elements(By.XPATH,"//span[@class='ellipsis clr']")
for i in Designation_tags:
    #time.sleep(5)
    try:
        Designation.append(i.text)
    except NoSuchElementException :
        Designation.append('Not present')
        
Company_tags=driver.find_elements(By.XPATH,"//a[@class='ellipsis']//i")
for i in Company_tags:
    #time.sleep(5)
    try:
        Company.append(i.text)
    except NoSuchElementException :
        Company.append('Not present')
        
Skills_tags=driver.find_elements(By.XPATH,"//div[@class='hireSec highlightable']")
for i in Skills_tags:
    #time.sleep(5)
    try:
        Skills.append(i.text)
    except NoSuchElementException :
        Skills.append('Not present')
        
Location_tags=driver.find_elements(By.XPATH,"//small[@class='ellipsis']")
for i in Location_tags:
    #time.sleep(5)
    try:
        Location.append(i.text)
    except NoSuchElementException :
        Location.append('Not present')

In [22]:
print(len(Name),len(Designation),len(Company),len(Skills),len(Location))

50 50 50 50 48

In [25]:
df=pd.DataFrame({'Name':Name,'Designation':Designation,'Company':Company,'Skills':Skills})
df

,Name,Designation,Company,Skills
0,Aakash Harit,HR Manager,,"Classic ASP Developer, Internet Marketing Prof..."
1,shravan Kumar Gaddam,Company Recruiter,,".Net, Java, Data Science, Linux Administration..."
2,MARSIAN Technologies LLP,Company HR,,"Data Science, Artificial Intelligence, Machine..."
3,Anik Agrawal,Company Recruiter,,"Mean Stack, javascript, angularjs, mongodb, We..."
4,subhas patel,Founder CEO,,"Hadoop, Spark, Digital Strategy, Data Architec..."
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,,"Analytics, Business Intelligence, Business Ana..."
6,Institute for Financial Management and Resear,Programme Manager,,Data Science
7,Balu Ramesh,HR Administrator,,"Machine Learning, algorithms, Go Getter, Compu..."
8,Asif Lucknowi,Director,,"Technical Training, Software Development, Pres..."
9,InstaFinancials,Human Resource,,"Software Development, It Sales, Account Manage..."
10,Vaishnavi Kudalkar,HR Executive,,"Data Science, Python, Data Analytics"
11,Priyanka Akiri,HR Manager,,"Oracle Dba, Data Science, Data Warehousing, ET..."
12,Kalpana Dumpala,Executive Hiring,,"Qa, Ui/ux, Java Developer, Java Architect, C++..."
13,Mubarak,Company HR,,"Business Intelligence, Data Warehousing, Data ..."
14,Kushal Rastogi,Company HR,,"Office Administration, Hr Administration, tele..."
15,Mahesh Babu Channa,HR Team Lead,,"Social Media, digital media maketing, seo, smm..."
16,Kapil Devang,HR Manager,,"Big Data, Hadoop, Data Analytics, Data Science"
17,Sakshi Chhikara,Assistant Manager HR,,"React.js, Data Science, Java, Front End, Busin..."
18,Ruchi Dhote,Senior Executive Talent Acquisition,,"Qlikview, Qlik Sense, Microsoft Azure, Power B..."
19,Manisha Yadav,HR Executive,,"Telecalling, Client Interaction, Marketing, Re..."
20,Riya Rajesh,Manager Talent Acquisition,,Data Science
21,Rashmi Bhattacharjee,HR Head,,"Corporate Sales, Software Development, Softwar..."
22,Faizan Kareem,HR MANAGER,,"Data Analytics, Data Science, Machine Learning..."
23,Rithika dadwal,HR Recruiter,,"Data Science, Machine Learning, Python, R, Dee..."
24,Sandhya Khandagale,HR Recruiter,,"Big Data, Data Science, Artificial Intelligenc..."
25,Shaun Rao,Manager Human Resources,,"Java, Net, Angularjs, Hr, Infrastructure, Mana..."
26,Azahar Shaikh,Company Recruiter,,"Data Science, Artificial Intelligence, Machine..."
27,Manas,Lead Talent acquisition,,"Software Architecture, Vp Engineering, Product..."
28,kumar,Proprietor,,"Data Science, Hadoop, Rpas, Devops, Python, Aw..."
29,Sunil Vedula,CEO,,"Signal Processing, Machine Learning, Neural Ne..."
30,Rajat Kumar,Founder CEO,,"Web Technologies, Project Management, Software..."
31,Dhruv Dev Dubey,Company Recruitment Head,,"Server Administartion, Verilog, Vhdl, Digital ..."
32,Jayanth N,Project Manager,,"Data Analytics, Managed Services, Team Leading..."
33,Avodha,Business Development Associate,,"Ethical Hacking, Security Operations Center, S..."
34,SREEDHAR,Recruitment Consultant,,"Data Science, Machine Learning, Big Data Analy..."
35,Priya Khare,Senior Manager,,"Data Science, Artificial Intelligence, analyti..."
36,Amit Sharma,Consultant,,"Machine Learning, Artificial Intelligence, Dat..."
37,Kanan,senior technology instructor,,"C, C++, Artificial Intelligence, Python, Php, ..."
38,Shashikant Chaudhary,HR Recruiter/HR Excutive,,"Relationship Management, Retail Sales, Private..."
39,Brad,"Manager, Technical Recruiting",,"Data Science, Software Engineering"
40,Rutuja Pawar,Technical Recruiter,,"Data Science, Big Data Analytics, Digital Mark..."
41,Madhusudhan Sridhar,Erp Implementer,,"Data Science, Recruitment, Salary"
42,Ankit Sinha,Head Analytics,,"B.Tech, Tableau, Statistics, R, Analytics, Tim..."
43,Gaurav Chouhan,Chief Technical Officer,,"Software Development, Business Intelligence, B..."
44,Rashi Kacker,Sr Product Manager,,"Data Science, Node.js, Angularjs"
45,Ashwini,Director Global Delivery,,"Data Science, Media Marketing, Resource Planni..."
46,Balaji Kolli,Co Founder,,"Data Analysis, Learning, Data Science, Compute..."
47,Rajani Nagaraj,HR Manager,,"Java, Hadoop, R, Machine Learning, Spark, Flum..."
48,ROHIT Kumar,Architect,,"Software Development, Core Java, Unit Testing,..."
49,Amir Chowdhury,Managing Partner,,"Machine Learning, Data Science, Product Manage..."

In [24]:
Location

['Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Ahmedabad',
 'UK - (london)',
 'Vadodara / Baroda',
 'Chennai',
 'Trivandrum',
 'Indore',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Hyderabad',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Hyderabad / Secunderabad',
 'Bhopal',
 'Chandigarh',
 'Pune',
 'Navi Mumbai',
 'Cochin',
 'Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Pune',
 'Pune',
 'Pune',
 'Bengaluru / Bangalore',
 'Bengaluru / Bangalore',
 'Delhi',
 'Bengaluru / Bangalore',
 'Mysoru / Mysore',
 'Hyderabad / Secunderabad',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'New Delhi',
 'Chennai',
 'Aligarh',
 'Salt Lake City',
 'Pune',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Indore',
 'Bengaluru / Bangalore',
 'MYSORE',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai']

In [ ]:
#Due to page access denied occuring I have written code only.I have checked absolute from my india friend.so i hvae not run this 
#code.
#I alredy raise this issue from ticket.

In [38]:
#Q8.

In [39]:
# Connect to webdriver
driver = webdriver.Chrome(r'C:\Users\COTMAC\Downloads\chromedriver_win32\chromedriver.exe')

C:\Users\COTMAC\AppData\Local\Temp/ipykernel_11408/2295598310.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r'C:\Users\COTMAC\Downloads\chromedriver_win32\chromedriver.exe')

In [40]:
driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')

In [43]:
Book_Name=[]
Author_Name=[]
Volumes_Sold=[]
Publisher=[]
Genre=[]

Book_Name_tags=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]//tbody//tr//td[2]')
for i in Book_Name_tags:
    #time.sleep(5)
    try:
        Book_Name.append(i.text)
    except NoSuchElementException :
        Book_Name.append('Not present')

Author_Name_tags=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]//tbody//tr//td[3]')
for i in Author_Name_tags:
    #time.sleep(5)
    try:
        Author_Name.append(i.text)
    except NoSuchElementException :
        Author_Name.append('Not present')
        
Volumes_Sold_tags=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]//tbody//tr//td[4]')
for i in Volumes_Sold_tags:
    #time.sleep(5)
    try:
        Volumes_Sold.append(i.text)
    except NoSuchElementException :
        Volumes_Sold.append('Not present')
        
Publisher_tags=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]//tbody//tr//td[5]')
for i in Publisher_tags:
    #time.sleep(5)
    try:
        Publisher.append(i.text)
    except NoSuchElementException :
        Publisher.append('Not present')
        
Genre_tags=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]//tbody//tr//td[6]')
for i in Genre_tags:
    #time.sleep(5)
    try:
        Genre.append(i.text)
    except NoSuchElementException :
        Genre.append('Not present')

In [44]:
print(len(Book_Name),len(Author_Name),len(Volumes_Sold),len(Publisher),len(Genre))

100 100 100 100 100

In [45]:
df=pd.DataFrame({'Book_Name':Book_Name,'Author_Name':Author_Name,'Volumes_Sold':Volumes_Sold,'Publisher':Publisher,'Genre':Genre})
df

,Book_Name,Author_Name,Volumes_Sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [ ]:
#Q9.

In [46]:
# Connect to webdriver
driver = webdriver.Chrome(r'C:\Users\COTMAC\Downloads\chromedriver_win32\chromedriver.exe')

C:\Users\COTMAC\AppData\Local\Temp/ipykernel_11408/2295598310.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r'C:\Users\COTMAC\Downloads\chromedriver_win32\chromedriver.exe')

In [47]:
driver.get('https://www.imdb.com/list/ls095964455/')

In [69]:
Series_name=[]
Series_Year_Span=[]
Series_Genre=[]
Series_Run_Time=[]
Series_Rating=[]
Series_Vote=[]


Series_name_tags=driver.find_elements(By.XPATH,"//h3[@class='lister-item-header']")
for i in Series_name_tags:
    #time.sleep(5)
    try:
        Series_name.append(i.text)
    except NoSuchElementException :
        Series_name.append('Not present')

Series_Year_Span_tags=driver.find_elements(By.XPATH,"//span[@class='lister-item-year text-muted unbold']")
for i in Series_Year_Span_tags:
    #time.sleep(5)
    try:
        Series_Year_Span.append(i.text)
    except NoSuchElementException :
        Series_Year_Span.append('Not present')
        
Series_Genre_tags=driver.find_elements(By.XPATH,"//span[@class='genre']")
for i in Series_Genre_tags:
    #time.sleep(5)
    try:
        Series_Genre.append(i.text)
    except NoSuchElementException :
        Series_Genre.append('Not present')
        
Series_Run_Time_tags=driver.find_elements(By.XPATH,"//span[@class='runtime']")
for i in Series_Run_Time_tags:
    #time.sleep(5)
    try:
        Series_Run_Time.append(i.text)
    except NoSuchElementException :
        Series_Run_Time.append('Not present')
        
Series_Rating_tags=driver.find_elements(By.XPATH,"//div[@class='ipl-rating-star small']")
for i in Series_Rating_tags:
    #time.sleep(5)
    try:
        Series_Rating.append(i.text)
    except NoSuchElementException :
        Series_Rating.append('Not present')
        
Series_Vote_tags=driver.find_elements(By.XPATH,"//p[@class='text-muted text-small']")
for i in Series_Vote_tags:
    #time.sleep(5)
    try:
        Series_Vote.append(i.text[2].split(","))
    except NoSuchElementException :
        Series_Vote.append('Not present')

In [70]:
print(len(Series_name),len(Series_Year_Span),len(Series_Genre),len(Series_Run_Time),len(Series_Rating),len(Series_Vote))

100 100 100 100 100 300

In [71]:
df=pd.DataFrame({'Series_name':Series_name,'Series_Year_Span':Series_Year_Span,'Series_Genre':Series_Genre,'Series_Run_Time':Series_Run_Time,'Series_Rating':Series_Rating})
df

,Series_name,Series_Year_Span,Series_Genre,Series_Run_Time,Series_Rating
0,1. Game of Thrones (2011–2019),(2011–2019),"Action, Adventure, Drama",57 min,9.2
1,2. Stranger Things (2016– ),(2016– ),"Drama, Fantasy, Horror",51 min,8.7
2,3. The Walking Dead (2010–2022),(2010–2022),"Drama, Horror, Thriller",44 min,8.2
3,4. 13 Reasons Why (2017–2020),(2017–2020),"Drama, Mystery, Thriller",60 min,7.5
4,5. The 100 (2014–2020),(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6
...,...,...,...,...,...
95,96. Reign (2013–2017),(2013–2017),Drama,42 min,7.4
96,97. A Series of Unfortunate Events (2017–2019),(2017–2019),"Adventure, Comedy, Drama",50 min,7.8
97,98. Criminal Minds (2005–2020),(2005–2020),"Crime, Drama, Mystery",42 min,8.1
98,99. Scream: The TV Series (2015–2019),(2015–2019),"Comedy, Crime, Drama",45 min,7.1
99,100. The Haunting of Hill House (2018),(2018),"Drama, Horror, Mystery",572 min,8.6

In [61]:
Series_Vote

['TV-MA | 57 min | Action, Adventure, Drama',
 'Stars: Emilia Clarke, Peter Dinklage, Kit Harington, Lena Headey',
 'Votes: 2,021,685',
 'TV-14 | 51 min | Drama, Fantasy, Horror',
 'Stars: Millie Bobby Brown, Finn Wolfhard, Winona Ryder, David Harbour',
 'Votes: 1,118,344',
 'TV-MA | 44 min | Drama, Horror, Thriller',
 'Stars: Andrew Lincoln, Norman Reedus, Melissa McBride, Lauren Cohan',
 'Votes: 959,897',
 'TV-MA | 60 min | Drama, Mystery, Thriller',
 'Stars: Dylan Minnette, Katherine Langford, Christian Navarro, Alisha Boe',
 'Votes: 286,960',
 'TV-14 | 43 min | Drama, Mystery, Sci-Fi',
 'Stars: Eliza Taylor, Bob Morley, Marie Avgeropoulos, Isaiah Washington',
 'Votes: 246,556',
 'TV-MA | 59 min | Comedy, Crime, Drama',
 'Stars: Taylor Schilling, Danielle Brooks, Taryn Manning, Emma Myles',
 'Votes: 298,646',
 'TV-14 | 45 min | Crime, Drama, Mystery',
 'Stars: Lili Reinhart, Camila Mendes, Cole Sprouse, K.J. Apa',
 'Votes: 142,063',
 'TV-14 | 41 min | Drama, Romance',
 'Stars: Ellen Pompeo, Chandra Wilson, James Pickens Jr., Justin Chambers',
 'Votes: 300,502',
 'TV-PG | 43 min | Action, Adventure, Drama',
 'Stars: Grant Gustin, Candice Patton, Danielle Panabaker, Carlos Valdes',
 'Votes: 342,362',
 'TV-14 | 42 min | Action, Adventure, Crime',
 'Stars: Stephen Amell, Katie Cassidy, David Ramsey, Susanna Thompson',
 'Votes: 428,410',
 'TV-MA | 70 min | Action, Crime, Drama',
 'Stars: Úrsula Corberó, Álvaro Morte, Itziar Ituño, Pedro Alonso',
 'Votes: 465,088',
 'TV-PG | 22 min | Comedy, Romance',
 'Stars: Johnny Galecki, Jim Parsons, Kaley Cuoco, Simon Helberg',
 'Votes: 792,622',
 'TV-MA | 60 min | Drama, Mystery, Sci-Fi',
 'Stars: Daniel Lapaine, Hannah John-Kamen, Michaela Coel, Beatrice Robertson-Jones',
 'Votes: 528,893',
 'TV-14 | 88 min | Crime, Drama, Mystery',
 'Stars: Benedict Cumberbatch, Martin Freeman, Una Stubbs, Rupert Graves',
 'Votes: 905,896',
 'TV-MA | 44 min | Action, Adventure, Drama',
 'Stars: Katheryn Winnick, Gustaf Skarsgård, Alexander Ludwig, Georgia Hirst',
 'Votes: 517,940',
 'TV-14 | 44 min | Drama, Mystery, Romance',
 'Stars: Troian Bellisario, Ashley Benson, Lucy Hale, Shay Mitchell',
 'Votes: 165,332',
 'TV-14 | 43 min | Drama, Fantasy, Horror',
 'Stars: Nina Dobrev, Paul Wesley, Ian Somerhalder, Kat Graham',
 'Votes: 315,406',
 'TV-MA | 60 min | Drama, Horror, Sci-Fi',
 'Stars: Lady Gaga, Kathy Bates, Angela Bassett, Sarah Paulson',
 'Votes: 310,614',
 'TV-MA | 49 min | Crime, Drama, Thriller',
 'Stars: Bryan Cranston, Aaron Paul, Anna Gunn, Betsy Brandt',
 'Votes: 1,790,436',
 'TV-14 | 42 min | Crime, Drama, Fantasy',
 'Stars: Tom Ellis, Lauren German, Kevin Alejandro, D.B. Woodside',
 'Votes: 314,585',
 'TV-14 | 44 min | Drama, Fantasy, Horror',
 'Stars: Jared Padalecki, Jensen Ackles, Jim Beaver, Misha Collins',
 'Votes: 435,600',
 'TV-14 | 44 min | Action, Crime, Drama',
 'Stars: Dominic Purcell, Wentworth Miller, Amaury Nolasco, Robert Knepper',
 'Votes: 524,681',
 'TV-14 | 43 min | Crime, Drama, Mystery',
 'Stars: Viola Davis, Billy Brown, Jack Falahee, Aja Naomi King',
 'Votes: 149,095',
 'TV-14 | 41 min | Action, Drama, Fantasy',
 "Stars: Tyler Posey, Holland Roden, Dylan O'Brien, Linden Ashby",
 'Votes: 145,508',
 'TV-14 | 22 min | Animation, Comedy',
 'Stars: Dan Castellaneta, Nancy Cartwright, Harry Shearer, Julie Kavner',
 'Votes: 400,309',
 'TV-PG | 60 min | Adventure, Fantasy, Romance',
 'Stars: Ginnifer Goodwin, Jennifer Morrison, Lana Parrilla, Robert Carlyle',
 'Votes: 222,414',
 'TV-MA | 49 min | Biography, Crime, Drama',
 'Stars: Pedro Pascal, Wagner Moura, Boyd Holbrook, Alberto Ammann',
 'Votes: 412,007',
 'TV-MA | 54 min | Action, Crime, Drama',
 "Stars: Charlie Cox, Vincent D'Onofrio, Deborah Ann Woll, Elden Henson",
 'Votes: 428,216',
 'TV-14 | 22 min | Comedy, Romance',
 'Stars: Jennifer Aniston, Courteney Cox, Lisa Kudrow, Matt LeBlanc',
 'Votes: 969,188',
 'TV-14 | 22 min | Comedy, Romance',
 'Stars: Josh Radnor, Jason Segel, Cobie Smulders, Neil Patrick Harris',
 'Votes: 671,311',
 'TV-14 | 44 min | Comedy, Drama',
 'Stars: Gabriel Macht, Patrick J. Adams, Meghan Markle, Sarah Rafferty',
 'Votes: 402,273',
 'TV-MA | 49 min | Crime, Drama, Thriller',
 'Stars: Rami Malek, Christian Slater, Carly Chaikin, Martin Wallström',
 'Votes: 380,006',
 'TV-14 | 45 min | Drama, Fantasy, Horror',
 'Stars: Joseph Morgan, Daniel Gillies, Claire Holt, Phoebe Tonkin',
 'Votes: 133,836',
 'TV-PG | 43 min | Action, Adventure, Drama',
 'Stars: Melissa Benoist, Chyler Leigh, David Harewood, Katie McGrath',
 'Votes: 123,126',
 'TV-14 | 42 min | Drama, Romance',
 'Stars: Blake Lively, Leighton Meester, Penn Badgley, Ed Westwick',
 'Votes: 171,985',
 'TV-MA | 60 min | Drama, Mystery, Sci-Fi',
 'Stars: Bae Doona, Jamie Clayton, Tina Desai, Tuppence Middleton',
 'Votes: 153,164',
 'TV-14 | 42 min | Action, Crime, Drama',
 'Stars: Ben McKenzie, Jada Pinkett Smith, Donal Logue, Camren Bicondova',
 'Votes: 228,172',
 'TV-MA | 62 min | Drama, Mystery, Sci-Fi',
 'Stars: Evan Rachel Wood, Jeffrey Wright, Ed Harris, Thandiwe Newton',
 'Votes: 489,729',
 'TV-MA | 56 min | Action, Crime, Drama',
 'Stars: Krysten Ritter, Rachael Taylor, Eka Darville, Carrie-Anne Moss',
 'Votes: 211,654',
 'TV-PG | 22 min | Comedy, Drama, Romance',
 "Stars: Ed O'Neill, Sofía Vergara, Julie Bowen, Ty Burrell",
 'Votes: 418,848',
 'TV-MA | 23 min | Animation, Adventure, Comedy',
 'Stars: Justin Roiland, Chris Parnell, Spencer Grammer, Sarah Chalke',
 'Votes: 489,644',
 'TV-14 | 42 min | Action, Drama, Fantasy',
 'Stars: Katherine McNamara, Dominic Sherwood, Alberto Rosende, Matthew Daddario',
 'Votes: 62,399',
 'TV-MA | 25 min | Adventure, Comedy, Crime',
 'Stars: Jessica Barden, Alex Lawther, Steve Oram, Christine Bottomley',
 'Votes: 183,295',
 'TV-MA | 51 min | Drama',
 'Stars: Kevin Spacey, Michel Gill, Robin Wright, Kate Mara',
 'Votes: 498,526',
 'TV-MA | 60 min | Crime, Drama, Mystery',
 'Stars: Louis Hofmann, Karoline Eichhorn, Lisa Vicari, Maja Schöne',
 'Votes: 365,621',
 'TV-MA | 60 min | Crime, Drama, Thriller',
 'Stars: Itzan Escamilla, Omar Ayuso, Miguel Bernardeau, Arón Piper',
 'Votes: 75,852',
 'TV-MA | 45 min | Comedy, Drama',
 'Stars: Asa Butterfield, Gillian Anderson, Ncuti Gatwa, Emma Mackey',
 'Votes: 268,626',
 'TV-MA | 46 min | Comedy, Drama',
 'Stars: Emmy Rossum, William H. Macy, Ethan Cutkosky, Jeremy Allen White',
 'Votes: 235,805',
 'TV-14 | 22 min | Comedy, Romance',
 'Stars: Zooey Deschanel, Jake Johnson, Max Greenfield, Hannah Simone',
 'Votes: 219,789',
 'TV-PG | 45 min | Action, Adventure, Drama',
 'Stars: Clark Gregg, Ming-Na Wen, Brett Dalton, Iain De Caestecker',
 'Votes: 215,485',
 'TV-MA | 45 min | Crime, Drama, Romance',
 'Stars: Penn Badgley, Victoria Pedretti, Ambyr Childers, Elizabeth Lail',
 'Votes: 231,247',
 'TV-MA | 53 min | Crime, Drama, Mystery',
 'Stars: Michael C. Hall, Jennifer Carpenter, David Zayas, James Remar',
 'Votes: 717,623',
 'TV-MA | 44 min | Drama, Horror, Sci-Fi',
 'Stars: Kim Dickens, Frank Dillane, Cliff Curtis, Rubén Blades',
 'Votes: 128,578',
 'TV-MA | 22 min | Animation, Comedy',
 'Stars: Seth MacFarlane, Alex Borstein, Seth Green, Mila Kunis',
 'Votes: 332,295',
 'TV-14 | 43 min | Crime, Drama, Mystery',
 'Stars: James Spader, Megan Boone, Diego Klattenhoff, Ryan Eggold',
 'Votes: 243,459',
 'TV-14 | 44 min | Adventure, Drama, Fantasy',
 'Stars: Jorge Garcia, Josh Holloway, Yunjin Kim, Evangeline Lilly',
 'Votes: 543,895',
 'TV-MA | 60 min | Crime, Drama',
 'Stars: Cillian Murphy, Paul Anderson, Sophie Rundle, Helen McCrory',
 'Votes: 517,071',
 'TV-14 | 44 min | Drama, Mystery',
 'Stars: Hugh Laurie, Omar Epps, Robert Sean Leonard, Jesse Spencer',
 'Votes: 454,764',
 'TV-14 | 42 min | Crime, Drama, Mystery',
 'Stars: Priyanka Chopra Jonas, Jake McLaughlin, Johanna Braddy, Aunjanue Ellis',
 'Votes: 60,735',
 'TV-MA | 44 min | Drama, Sci-Fi, Thriller',
 'Stars: Tatiana Maslany, Dylan Bruce, Jordan Gavaris, Kevin Hanchard',
 'Votes: 109,811',
 'TV-MA | 55 min | Crime, Drama, Mystery',
 'Stars: Claire Danes, Mandy Patinkin, Damian Lewis, Rupert Friend',
 'Votes: 337,989',
 'TV-14 | 42 min | Action, Crime, Drama',
 'Stars: Sullivan Stapleton, Jaimie Alexander, Audrey Esparza, Ashley Johnson',
 'Votes: 73,269',
 'TV-14 | 42 min | Action, Adventure, Drama',
 'Stars: Caity Lotz, Amy Louise Pemberton, Dominic Purcell, Nick Zano',
 'Votes: 103,875',
 'TV-MA | 60 min | Drama, Thriller',
 'Stars: Elisabeth Moss, Yvonne Strahovski, Joseph Fiennes, Ann Dowd',
 'Votes: 221,894',
 'TV-14 | 60 min | Drama, Fantasy, Horror',
 'Stars: Kiernan Shipka, Ross Lynch, Lucy Davis, Chance Perdomo',
 'Votes: 92,427',
 'TV-14 | 41 min | Drama',
 'Stars: Freddie Highmore, Hill Harper, Richard Schiff, Christina Chang',
 'Votes: 91,570',
 'TV-PG | 60 min | Comedy',
 'Stars: Gina Rodriguez, Andrea Navedo, Yael Grobglas, Justin Baldoni',
 'Votes: 49,235',
 'TV-PG | 44 min | Comedy, Drama, Music',
 'Stars: Lea Michele, Jane Lynch, Matthew Morrison, Cory Monteith',
 'Votes: 147,213',
 'TV-MA | 22 min | Animation, Comedy',
 'Stars: Trey Parker, Matt Stone, Isaac Hayes, Mona Marshall',
 'Votes: 364,045',
 'TV-14 | 22 min | Comedy, Crime',
 'Stars: Andy Samberg, Stephanie Beatriz, Terry Crews, Melissa Fumero',
 'Votes: 302,775',
 'TV-14 | 43 min | Drama, Mystery, Sci-Fi',
 'Stars: Mike Vogel, Rachelle Lefevre, Alexander Koch, Colin Ford',
 'Votes: 106,119',
 'TV-14 | 60 min | Action, Adventure, Comedy',
 'Stars: Elliot Page, Tom Hopper, David Castañeda, Emmy Raver-Lampman',
 'Votes: 235,252',
 'TV-MA | 55 min | Crime, Drama, Mystery',
 'Stars: Vince Vaughn, Colin Farrell, Rachel McAdams, Taylor Kitsch',
 'Votes: 556,785',
 'TV-MA | 60 min | Drama, Fantasy, Mystery',
 'Stars: Brit Marling, Jason Isaacs, Scott Wilson, Alice Krige',
 'Votes: 103,477',
 'TV-14 | 45 min | Comedy, Drama, Mystery',
 'Stars: Teri Hatcher, Felicity Huffman, Marcia Cross, Eva Longoria',
 'Votes: 127,405',
 'TV-MA | 46 min | Crime, Drama',
 'Stars: Bob Odenkirk, Rhea Seehorn, Jonathan Banks, Michael Mando',
 'Votes: 452,547',
 'TV-MA | 45 min | Drama, Horror, Mystery',
 'Stars: Vera Farmiga, Freddie Highmore, Max Thieriot, Nicola Peltz Beckham',
 'Votes: 106,549',
 'TV-MA | 53 min | Action, Crime, Drama',
 'Stars: Jon Bernthal, Amber Rose Revah, Ben Barnes, Jason R. Moore',
 'Votes: 227,151',
 'TV-MA | 30 min | Comedy, Drama',
 'Stars: Jennifer Jason Leigh, Keir Gilchrist, Brigette Lundy-Paine, Michael Rapaport',
 'Votes: 85,857',
 'TV-14 | 42 min | Drama',
 'Stars: Elizabeth Gillies, Rafael de la Fuente, Robert Christopher Riley, Sam Adegoke',
 'Votes: 21,760',
 'TV-14 | 45 min | Comedy, Drama, Romance',
 'Stars: Milo Ventimiglia, Mandy Moore, Sterling K. Brown, Chrissy Metz',
 'Votes: 140,387',
 'TV-PG | 22 min | Comedy, Drama, Fantasy',
 "Stars: Kristen Bell, William Jackson Harper, Jameela Jamil, D'Arcy Carden",
 'Votes: 153,934',
 'TV-MA | 55 min | Action, Adventure, Crime',
 'Stars: Finn Jones, Jessica Henwick, Jessica Stroup, Tom Pelphrey',
 'Votes: 128,993',
 'TV-MA | 45 min | Drama, Sci-Fi, Thriller',
 'Stars: Alba August, Lucas Lynggaard Tønnesen, Mikkel Boe Følsgaard, Lukas Løkken',
 'Votes: 36,571',
 'TV-MA | 60 min | Crime, Drama, Mystery',
 'Stars: Jonathan Groff, Holt McCallany, Anna Torv, Hannah Gross',
 'Votes: 276,987',
 'TV-14 | 44 min | Drama, Mystery, Thriller',
 'Stars: Madeleine Stowe, Emily VanCamp, Gabriel Mann, Nick Wechsler',
 'Votes: 119,550',
 'TV-MA | 55 min | Action, Crime, Drama',
 'Stars: Mike Colter, Simone Missick, Theo Rossi, Alfre Woodard',
 'Votes: 129,318',
 'TV-14 | 43 min | Drama, Thriller',
 'Stars: Kerry Washington, Darby Stanchfield, Katie Lowes, Guillermo Díaz',
 'Votes: 73,217',
 'TV-MA | 50 min | Action, Adventure, Crime',
 'Stars: Charlie Cox, Krysten Ritter, Mike Colter, Finn Jones',
 'Votes: 105,490',
 'TV-MA | 60 min | Crime, Drama, Mystery',
 'Stars: Reese Witherspoon, Nicole Kidman, Shailene Woodley, Adam Scott',
 'Votes: 193,331',
 'TV-MA | 45 min | Comedy, Drama, Thriller',
 'Stars: Dallas Roberts, Debby Ryan, Christopher Gorham, Kimmy Shields',
 'Votes: 28,186',
 'TV-14 | 43 min | Crime, Drama, Mystery',
 'Stars: Simon Baker, Robin Tunney, Tim Kang, Owain Yeoman',
 'Votes: 182,406',
 'TV-MA | 58 min | Biography, Drama, History',
 'Stars: Claire Foy, Olivia Colman, Imelda Staunton, Matt Smith',
 'Votes: 195,152',
 'TV-MA | 330 min | Drama, History, Thriller',
 'Stars: Jessie Buckley, Jared Harris, Stellan Skarsgård, Adam Nagaitis',
 'Votes: 721,649',
 'TV-14 | 42 min | Comedy, Crime, Drama',
 'Stars: Rose McIver, Malcolm Goodwin, Rahul Kohli, Robert Buckley',
 'Votes: 67,378',
 'TV-14 | 42 min | Drama',
 'Stars: Adelaide Kane, Megan Follows, Celina Sinden, Torrance Coombs',
 'Votes: 49,269',
 'TV-PG | 50 min | Adventure, Comedy, Drama',
 'Stars: Neil Patrick Harris, Patrick Warburton, Malina Weissman, Louis Hynes',
 'Votes: 60,170',
 'TV-14 | 42 min | Crime, Drama, Mystery',
 'Stars: Matthew Gray Gubler, Kirsten Vangsness, A.J. Cook, Joe Mantegna',
 'Votes: 193,427',
 'TV-14 | 45 min | Comedy, Crime, Drama',
 'Stars: Willa Fitzgerald, Bex Taylor-Klaus, John Karna, Carlson Young',
 'Votes: 40,809',
 'TV-MA | 572 min | Drama, Horror, Mystery',
 'Stars: Michiel Huisman, Carla Gugino, Henry Thomas, Elizabeth Reaser',
 'Votes: 233,425']

In [ ]:
#Q10.

In [28]:
# Connect to webdriver
driver = webdriver.Chrome(r'C:\Users\COTMAC\Downloads\chromedriver_win32\chromedriver.exe')

C:\Users\COTMAC\AppData\Local\Temp/ipykernel_18980/2295598310.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r'C:\Users\COTMAC\Downloads\chromedriver_win32\chromedriver.exe')

In [29]:
driver.get('https://archive.ics.uci.edu/')

In [30]:
pop_up=driver.find_element(By.XPATH,"/html/body/table[1]/tbody/tr/td[2]/span[2]/a/font/b")
pop_up.click()

In [31]:
Dataset_Name=[]
Data_Type=[]
Task=[]
Instances=[]
Attributes=[]
Year=[]


Dataset_Name_tags=driver.find_elements(By.XPATH,"//p[@class='normal']//b//a")
for i in Dataset_Name_tags:
    #time.sleep(5)
    try:
        Dataset_Name.append(i.text)
    except NoSuchElementException :
        Dataset_Name.append('Not present')

Data_Type_tags=driver.find_elements(By.XPATH,"//table[@class='cellpadding']//tbody//tr//td[2]//table[2]//tbody//tr[2]//td[1]//table//tbody//tr//td[3]")
for i in Data_Type_tags:
    #time.sleep(5)
    try:
        Data_Type.append(i.text)
    except NoSuchElementException :
        Data_Type.append('Not present')
        
Task_tags=driver.find_elements(By.XPATH,"//table[@class='cellpadding']//tbody//tr//td[2]//table[2]//tbody//tr[2]//td[1]//table//tbody//tr//td[3]")
for i in Task_tags:
    #time.sleep(5)
    try:
        Task.append(i.text)
    except NoSuchElementException :
        Task.append('Not present')
        
Instances_tags=driver.find_elements(By.XPATH,"//table[@class='cellpadding']//tbody//tr//td[2]//table[2]//tbody//tr[2]//td[1]//table//tbody//tr//td[4]")
for i in Instances_tags:
    #time.sleep(5)
    try:
        Instances.append(i.text)
    except NoSuchElementException :
        Instances.append('Not present')
        
Attributes_tags=driver.find_elements(By.XPATH,"//table[@class='cellpadding']//tbody//tr//td[2]//table[2]//tbody//tr[2]//td[1]//table//tbody//tr//td[5]")
for i in Attributes_tags:
    #time.sleep(5)
    try:
        Attributes.append(i.text)
    except NoSuchElementException :
        Attributes.append('Not present')
        
Year_tags=driver.find_elements(By.XPATH,"//table[@class='cellpadding']//tbody//tr//td[2]//table[2]//tbody//tr[2]//td[1]//table//tbody//tr//td[6]")
for i in Year_tags:
    #time.sleep(5)
    try:
        Year.append(i.text)
    except NoSuchElementException :
        Year.append('Not present')

In [ ]:
print(len(Dataset_Name),len(Data_Type),len(Task),len(Instances),len(Attributes),len(Year))

In [ ]:
df=pd.DataFrame({'Dataset_Name':Dataset_Name,'Data_Type':Data_Type,'Task':Task,'Instances':Instances,'Attributes':Attributes,'Year':Year})
df

In [123]:
Dataset_Name=[]

#Dataset_Name_tags=driver.find_elements(By.XPATH,"//table[@class='cellpadding']//tbody//tr//td[2]//table[2]//tbody//tr[2]//td[1]//table//tbody//tr//td[2]")
Dataset_Name_tags=driver.find_elements(By.XPATH,"//p[@class='normal']//b//a")
for i in Dataset_Name_tags:
    #time.sleep(5)
    try:
        Dataset_Name.append(i.text)
    except NoSuchElementException :
        Dataset_Name.append('Not present')

In [124]:
Dataset_Name

['Abalone',
 'Adult',
 'Annealing',
 'Anonymous Microsoft Web Data',
 'Arrhythmia',
 'Artificial Characters',
 'Audiology (Original)',
 'Audiology (Standardized)',
 'Auto MPG',
 'Automobile',
 'Badges',
 'Balance Scale',
 'Balloons',
 'Breast Cancer',
 'Breast Cancer Wisconsin (Original)',
 'Breast Cancer Wisconsin (Prognostic)',
 'Breast Cancer Wisconsin (Diagnostic)',
 'Pittsburgh Bridges',
 'Car Evaluation',
 'Census Income',
 'Chess (King-Rook vs. King-Knight)',
 'Chess (King-Rook vs. King-Pawn)',
 'Chess (King-Rook vs. King)',
 'Chess (Domain Theories)',
 'Bach Chorales',
 'Connect-4',
 'Credit Approval',
 'Japanese Credit Screening',
 'Computer Hardware',
 'Contraceptive Method Choice',
 'Covertype',
 'Cylinder Bands',
 'Dermatology',
 'Diabetes',
 'DGP2 - The Second Data Generation Program',
 'Document Understanding',
 'EBL Domain Theories',
 'Echocardiogram',
 'Ecoli',
 'Flags',
 'Function Finding',
 'Glass Identification',
 "Haberman's Survival",
 'Hayes-Roth',
 'Heart Disease',
 'Hepatitis',
 'Horse Colic',
 'ICU',
 'Image Segmentation',
 'Internet Advertisements',
 'Ionosphere',
 'Iris',
 'ISOLET',
 'Kinship',
 'Labor Relations',
 'LED Display Domain',
 'Lenses',
 'Letter Recognition',
 'Liver Disorders',
 'Logic Theorist',
 'Lung Cancer',
 'Lymphography',
 'Mechanical Analysis',
 'Meta-data',
 'Mobile Robots',
 'Molecular Biology (Promoter Gene Sequences)',
 'Molecular Biology (Protein Secondary Structure)',
 'Molecular Biology (Splice-junction Gene Sequences)',
 "MONK's Problems",
 'Moral Reasoner',
 'Multiple Features',
 'Mushroom',
 'Musk (Version 1)',
 'Musk (Version 2)',
 'Nursery',
 'Othello Domain Theory',
 'Page Blocks Classification',
 'Optical Recognition of Handwritten Digits',
 'Pen-Based Recognition of Handwritten Digits',
 'Post-Operative Patient',
 'Primary Tumor',
 'Prodigy',
 'Qualitative Structure Activity Relationships',
 'Quadruped Mammals',
 'Servo',
 'Shuttle Landing Control',
 'Solar Flare',
 'Soybean (Large)',
 'Soybean (Small)',
 'Challenger USA Space Shuttle O-Ring',
 'Low Resolution Spectrometer',
 'Spambase',
 'SPECT Heart',
 'SPECTF Heart',
 'Sponge',
 'Statlog Project',
 'Student Loan Relational',
 'Teaching Assistant Evaluation',
 'Tic-Tac-Toe Endgame',
 'Thyroid Disease',
 'Trains',
 'University',
 'Congressional Voting Records',
 'Water Treatment Plant',
 'Waveform Database Generator (Version 1)',
 'Waveform Database Generator (Version 2)',
 'Wine',
 'Yeast',
 'Zoo',
 'Undocumented',
 'Twenty Newsgroups',
 'Australian Sign Language signs',
 'Australian Sign Language signs (High Quality)',
 'US Census Data (1990)',
 'Census-Income (KDD)',
 'Coil 1999 Competition Data',
 'Corel Image Features',
 'E. Coli Genes',
 'EEG Database',
 'El Nino',
 'Entree Chicago Recommendation Data',
 'CMU Face Images',
 'Insurance Company Benchmark (COIL 2000)',
 'Internet Usage Data',
 'IPUMS Census Database',
 'Japanese Vowels',
 'KDD Cup 1998 Data',
 'KDD Cup 1999 Data',
 'M. Tuberculosis Genes',
 'Movie',
 'MSNBC.com Anonymous Web Data',
 'NSF Research Award Abstracts 1990-2003',
 'Pioneer-1 Mobile Robot Data',
 'Pseudo Periodic Synthetic Time Series',
 'Reuters-21578 Text Categorization Collection',
 'Robot Execution Failures',
 'Synthetic Control Chart Time Series',
 'Syskill and Webert Web Page Ratings',
 'UNIX User Data',
 'Volcanoes on Venus - JARtool experiment',
 'Statlog (Australian Credit Approval)',
 'Statlog (German Credit Data)',
 'Statlog (Heart)',
 'Statlog (Landsat Satellite)',
 'Statlog (Image Segmentation)',
 'Statlog (Shuttle)',
 'Statlog (Vehicle Silhouettes)',
 'Connectionist Bench (Nettalk Corpus)',
 'Connectionist Bench (Sonar, Mines vs. Rocks)',
 'Connectionist Bench (Vowel Recognition - Deterding Data)',
 'Economic Sanctions',
 'Protein Data',
 'Cloud',
 'CalIt2 Building People Counts',
 'Dodgers Loop Sensor',
 'Poker Hand',
 'MAGIC Gamma Telescope',
 'UJI Pen Characters',
 'Mammographic Mass',
 'Forest Fires',
 'Reuters Transcribed Subset',
 'Bag of Words',
 'Concrete Compressive Strength',
 'Hill-Valley',
 'Arcene',
 'Dexter',
 'Dorothea',
 'Gisette',
 'Madelon',
 'Ozone Level Detection',
 'Abscisic Acid Signaling Network',
 'Parkinsons',
 'Character Trajectories',
 'Blood Transfusion Service Center',
 'UJI Pen Characters (Version 2)',
 'Semeion Handwritten Digit',
 'SECOM',
 'Plants',
 'Libras Movement',
 'Concrete Slump Test',
 'Communities and Crime',
 'Acute Inflammations',
 'Wine Quality',
 'URL Reputation',
 'p53 Mutants',
 'Parkinsons Telemonitoring',
 'Demospongiae',
 'Opinosis Opinion ⁄ Review',
 'Breast Tissue',
 'Cardiotocography',
 'Wall-Following Robot Navigation Data',
 'Spoken Arabic Digit',
 'Localization Data for Person Activity',
 'AutoUniv',
 'Steel Plates Faults',
 'MiniBooNE particle identification',
 'YearPredictionMSD',
 'PEMS-SF',
 'OpinRank Review Dataset',
 'Relative location of CT slices on axial axis',
 'Online Handwritten Assamese Characters Dataset',
 'PubChem Bioassay Data',
 'Record Linkage Comparison Patterns',
 'Communities and Crime Unnormalized',
 'Vertebral Column',
 'EMG Physical Action Data Set',
 'Vicon Physical Action Data Set',
 'Amazon Commerce reviews set',
 'Amazon Access Samples',
 'Reuter_50_50',
 'Farm Ads',
 'DBWorld e-mails',
 'KEGG Metabolic Relation Network (Directed)',
 'KEGG Metabolic Reaction Network (Undirected)',
 'Bank Marketing',
 'YouTube Comedy Slam Preference Data',
 'Gas Sensor Array Drift Dataset',
 'ILPD (Indian Liver Patient Dataset)',
 'OPPORTUNITY Activity Recognition',
 'Nomao',
 'SMS Spam Collection',
 'Skin Segmentation',
 'Planning Relax',
 'PAMAP2 Physical Activity Monitoring',
 'Restaurant & consumer data',
 'CNAE-9',
 'Individual household electric power consumption',
 'seeds',
 'Northix',
 'QtyT40I10D100K',
 'Legal Case Reports',
 'Human Activity Recognition Using Smartphones',
 'One-hundred plant species leaves data set',
 'Energy efficiency',
 'Yacht Hydrodynamics',
 'Fertility',
 'Daphnet Freezing of Gait',
 '3D Road Network (North Jutland, Denmark)',
 'ISTANBUL STOCK EXCHANGE',
 'Buzz in social media',
 'First-order theorem proving',
 'Wearable Computing: Classification of Body Postures and Movements (PUC-Rio)',
 'Gas sensor arrays in open sampling settings',
 'Climate Model Simulation Crashes',
 'MicroMass',
 'QSAR biodegradation',
 'BLOGGER',
 'Daily and Sports Activities',
 'User Knowledge Modeling',
 'Reuters RCV1 RCV2 Multilingual, Multiview Text Categorization Test collection',
 'NYSK',
 'Turkiye Student Evaluation',
 "ser Knowledge Modeling Data (Students' Knowledge Levels on DC Electrical Machines)",
 'EEG Eye State',
 'Physicochemical Properties of Protein Tertiary Structure',
 'seismic-bumps',
 'banknote authentication',
 'USPTO Algorithm Challenge, run by NASA-Harvard Tournament Lab and TopCoder Problem: Pat',
 'YouTube Multiview Video Games Dataset',
 'Gas Sensor Array Drift Dataset at Different Concentrations',
 'Activities of Daily Living (ADLs) Recognition Using Binary Sensors',
 'SkillCraft1 Master Table Dataset',
 'Weight Lifting Exercises monitored with Inertial Measurement Units',
 'SML2010',
 'Bike Sharing Dataset',
 'Predict keywords activities in a online social media',
 'Thoracic Surgery Data',
 'EMG dataset in Lower Limb',
 'SUSY',
 'HIGGS',
 'Qualitative_Bankruptcy',
 'LSVT Voice Rehabilitation',
 'Dataset for ADL Recognition with Wrist-worn Accelerometer',
 'Wilt',
 'User Identification From Walking Activity',
 'Activity Recognition from Single Chest-Mounted Accelerometer',
 'Leaf',
 'Dresses_Attribute_Sales',
 'Tamilnadu Electricity Board Hourly Readings',
 'Airfoil Self-Noise',
 'Wholesale customers',
 'Twitter Data set for Arabic Sentiment Analysis',
 'Combined Cycle Power Plant',
 'Urban Land Cover',
 'Diabetes 130-US hospitals for years 1999-2008',
 'Bach Choral Harmony',
 'StoneFlakes',
 'Tennis Major Tournament Match Statistics',
 'Parkinson Speech Dataset with Multiple Types of Sound Recordings',
 'Gesture Phase Segmentation',
 'Perfume Data',
 'BlogFeedback',
 'REALDISP Activity Recognition Dataset',
 'Newspaper and magazine images segmentation dataset',
 'AAAI 2014 Accepted Papers',
 'Gas sensor array under flow modulation',
 'Gas sensor array exposed to turbulent gas mixtures',
 'UJIIndoorLoc',
 'Sentence Classification',
 'Dow Jones Index',
 'sEMG for Basic Hand movements',
 'AAAI 2013 Accepted Papers',
 'Geographical Original of Music',
 'Condition Based Maintenance of Naval Propulsion Plants',
 'Grammatical Facial Expressions',
 'NoisyOffice',
 'MHEALTH Dataset',
 'Student Performance',
 'ElectricityLoadDiagrams20112014',
 'Gas sensor array under dynamic gas mixtures',
 'microblogPCU',
 'Firm-Teacher_Clave-Direction_Classification',
 'Dataset for Sensorless Drive Diagnosis',
 'TV News Channel Commercial Detection Dataset',
 'Phishing Websites',
 'Greenhouse Gas Observing Network',
 'Diabetic Retinopathy Debrecen Data Set',
 'HIV-1 protease cleavage',
 'Sentiment Labelled Sentences',
 'Online News Popularity',
 'Forest type mapping',
 'wiki4HE',
 'Online Video Characteristics and Transcoding Time Dataset',
 'Chronic_Kidney_Disease',
 'Machine Learning based ZZAlpha Ltd. Stock Recommendations 2012-2014',
 'Folio',
 'Taxi Service Trajectory - Prediction Challenge, ECML PKDD 2015',
 'Cuff-Less Blood Pressure Estimation',
 'Smartphone-Based Recognition of Human Activities and Postural Transitions',
 'Mice Protein Expression',
 'UJIIndoorLoc-Mag',
 'Heterogeneity Activity Recognition',
 'Educational Process Mining (EPM): A Learning Analytics Data Set',
 'HEPMASS',
 'Indoor User Movement Prediction from RSS data',
 'Open University Learning Analytics dataset',
 'default of credit card clients',
 'Mesothelioma’s disease data set',
 'Online Retail',
 'SIFT10M',
 'GPS Trajectories',
 'Detect Malacious Executable(AntiVirus)',
 'Occupancy Detection',
 'Improved Spiral Test Using Digitized Graphics Tablet for Monitoring Parkinson’s Disease',
 'News Aggregator',
 'Air Quality',
 'Twin gas sensor arrays',
 'Gas sensors for home activity monitoring',
 'Facebook Comment Volume Dataset',
 'Smartphone Dataset for Human Activity Recognition (HAR) in Ambient Assisted Living (AAL)',
 'Polish companies bankruptcy data',
 'Activity Recognition system based on Multisensor data fusion (AReM)',
 'Dota2 Games Results',
 'Facebook metrics',
 'UbiqLog (smartphone lifelogging)',
 'NIPS Conference Papers 1987-2015',
 'HTRU2',
 'Drug consumption (quantified)',
 'Appliances energy prediction',
 'Miskolc IIS Hybrid IPS',
 'KDC-4007 dataset Collection',
 'Geo-Magnetic field and WLAN dataset for indoor localisation from wristband and smartphone',
 'DrivFace',
 'Website Phishing',
 'YouTube Spam Collection',
 'Beijing PM2.5 Data',
 'Cargo 2000 Freight Tracking and Tracing',
 'Cervical cancer (Risk Factors)',
 'Quality Assessment of Digital Colposcopies',
 'KASANDR',
 'FMA: A Dataset For Music Analysis',
 'Air quality',
 'Epileptic Seizure Recognition',
 'Devanagari Handwritten Character Dataset',
 'Stock portfolio performance',
 'MoCap Hand Postures',
 'Early biomarkers of Parkinson�s disease based on natural connected speech',
 'Data for Software Engineering Teamwork Assessment in Education Setting',
 'PM2.5 Data of Five Chinese Cities',
 'Parkinson Disease Spiral Drawings Using Digitized Graphics Tablet',
 'Sales_Transactions_Dataset_Weekly',
 'Las Vegas Strip',
 'Eco-hotel',
 'MEU-Mobile KSD',
 'Crowdsourced Mapping',
 'gene expression cancer RNA-Seq',
 'Hybrid Indoor Positioning Dataset from WiFi RSSI, Bluetooth and magnetometer',
 'chestnut – LARVIC',
 'Burst Header Packet (BHP) flooding attack on Optical Burst Switching (OBS) Network',
 'Motion Capture Hand Postures',
 'Anuran Calls (MFCCs)',
 'TTC-3600: Benchmark dataset for Turkish text categorization',
 'Gastrointestinal Lesions in Regular Colonoscopy',
 'Daily Demand Forecasting Orders',
 'Paper Reviews',
 'extention of Z-Alizadeh sani dataset',
 'Z-Alizadeh Sani',
 'Dynamic Features of VirusShare Executables',
 'IDA2016Challenge',
 'DSRC Vehicle Communications',
 'Mturk User-Perceived Clusters over Images',
 'Character Font Images',
 'DeliciousMIL: A Data Set for Multi-Label Multi-Instance Learning with Instance Labels',
 'Autistic Spectrum Disorder Screening Data for Children',
 'Autistic Spectrum Disorder Screening Data for Adolescent',
 'APS Failure at Scania Trucks',
 'Wireless Indoor Localization',
 'HCC Survival',
 'CSM (Conventional and Social Media Movies) Dataset 2014 and 2015',
 'University of Tehran Question Dataset 2016 (UTQD.2016)',
 'Autism Screening Adult',
 'Activity recognition with healthy older people using a batteryless wearable sensor',
 'Immunotherapy Dataset',
 'Cryotherapy Dataset',
 'OCT data & Color Fundus Images of Left & Right Eyes',
 'Discrete Tone Image Dataset',
 'News Popularity in Multiple Social Media Platforms',
 'Ultrasonic flowmeter diagnostics',
 'ICMLA 2014 Accepted Papers Data Set',
 'BLE RSSI Dataset for Indoor localization and Navigation',
 'Container Crane Controller Data Set',
 'Residential Building Data Set',
 'Health News in Twitter',
 'chipseq',
 'SGEMM GPU kernel performance',
 'Repeat Consumption Matrices',
 'detection_of_IoT_botnet_attacks_N_BaIoT',
 'Absenteeism at work',
 'SCADI',
 'Condition monitoring of hydraulic systems',
 'Carbon Nanotubes',
 'Optical Interconnection Network',
 'Sports articles for objectivity analysis',
 'Breast Cancer Coimbra',
 'GNFUV Unmanned Surface Vehicles Sensor Data',
 'Dishonest Internet users Dataset',
 'Victorian Era Authorship Attribution',
 'Simulated Falls and Daily Living Activities Data Set',
 'Multimodal Damage Identification for Humanitarian Computing',
 'EEG Steady-State Visual Evoked Potential Signals',
 'Roman Urdu Data Set',
 'Avila',
 'PANDOR',
 'Drug Review Dataset (Druglib.com)',
 'Drug Review Dataset (Drugs.com)',
 'Physical Unclonable Functions',
 'Superconductivty Data',
 'WESAD (Wearable Stress and Affect Detection)',
 'GNFUV Unmanned Surface Vehicles Sensor Data Set 2',
 'Student Academics Performance',
 'Online Shoppers Purchasing Intention Dataset',
 'PMU-UD',
 "Parkinson's Disease Classification",
 'Electrical Grid Stability Simulated Data',
 'Caesarian Section Classification Dataset',
 'BAUM-1',
 'BAUM-2',
 'Audit Data',
 'BuddyMove Data Set',
 'Real estate valuation data set',
 'Early biomarkers of Parkinson’s disease based on natural connected speech Data Set',
 'Somerville Happiness Survey',
 '2.4 GHZ Indoor Channel Measurements',
 'EMG data for gestures',
 'Parking Birmingham',
 'Behavior of the urban traffic of the city of Sao Paulo in Brazil',
 'Travel Reviews',
 'Tarvel Review Ratings',
 'Rice Leaf Diseases',
 'Gas sensor array temperature modulation',
 'Facebook Live Sellers in Thailand',
 'Parkinson Dataset with replicated acoustic features',
 'Metro Interstate Traffic Volume',
 'Query Analytics Workloads Dataset',
 'Wave Energy Converters',
 'PPG-DaLiA',
 'Alcohol QCM Sensor Dataset',
 'Divorce Predictors data set',
 'Incident management process enriched event log',
 'Opinion Corpus for Lebanese Arabic Reviews (OCLAR)',
 'MEx',
 'Beijing Multi-Site Air-Quality Data',
 'Online Retail II',
 'Hepatitis C Virus (HCV) for Egyptian patients',
 'QSAR fish toxicity',
 'QSAR aquatic toxicity',
 'Human Activity Recognition from Continuous Ambient Sensor Data',
 'WISDM Smartphone and Smartwatch Activity and Biometrics Dataset',
 'QSAR oral toxicity',
 'QSAR androgen receptor',
 'QSAR Bioconcentration classes dataset',
 'QSAR fish bioconcentration factor (BCF)',
 'A study of Asian Religious and Biblical Texts',
 'Real-time Election Results: Portugal 2019',
 'Bias correction of numerical prediction model temperature forecast',
 'Bar Crawl: Detecting Heavy Drinking',
 'Kitsune Network Attack Dataset',
 'Shoulder Implant X-Ray Manufacturer Classification',
 'Speaker Accent Recognition',
 'Heart failure clinical records',
 'Deepfakes: Medical Image Tamper Detection',
 'selfBACK',
 'South German Credit',
 'Exasens',
 'Swarm Behaviour',
 'Crop mapping using fused optical-radar data set',
 'BitcoinHeistRansomwareAddressDataset',
 'Facebook Large Page-Page Network',
 'Amphibians',
 'Early stage diabetes risk prediction dataset.',
 'Turkish Spam V01',
 'Stock keeping units',
 'Demand Forecasting for a store',
 'Detect Malware Types',
 'Wave Energy Converters',
 'Youtube cookery channels viewers comments in Hinglish',
 'Pedestrian in Traffic Dataset',
 'Cervical Cancer Behavior Risk',
 'Sattriya_Dance_Single_Hand_Gestures Dataset',
 'Divorce Predictors data set',
 '3W dataset',
 'Malware static and dynamic features VxHeaven and Virus Total',
 'Internet Firewall Data',
 'User Profiling and Abusive Language Detection Dataset',
 'Estimation of obesity levels based on eating habits and physical condition',
 'Rice (Cammeo and Osmancik)',
 'Vehicle routing and scheduling problems',
 'Algerian Forest Fires Dataset',
 'Breath Metabolomics',
 'Horton General Hospital',
 'UrbanGB, urban road accidents coordinates labelled by the urban center',
 'Gas Turbine CO and NOx Emission Data Set',
 'Activity recognition using wearable physiological measurements',
 'clickstream data for online shopping',
 'CNNpred: CNN-based stock market prediction using a diverse set of variables',
 'Apartment for rent classified',
 ': Simulated Data set of Iraqi tourism places',
 'Nasarian CAD Dataset',
 'Monolithic Columns in Troad and Mysia Region',
 'Bar Crawl: Detecting Heavy Drinking',
 'Seoul Bike Sharing Demand',
 'Person Classification Gait Data',
 'Shill Bidding Dataset',
 'Iranian Churn Dataset',
 'Unmanned Aerial Vehicle (UAV) Intrusion Detection',
 'Bone marrow transplant: children',
 'Exasens',
 'COVID-19 Surveillance',
 'Refractive errors',
 'Shoulder Implant X-Ray Manufacturer Classification',
 'CLINC150',
 'HCV data',
 'Taiwanese Bankruptcy Prediction',
 'South German Credit (UPDATE)',
 'IIWA14-R820-Gazebo-Dataset-10Trajectories',
 'Guitar Chords finger positions',
 'Russian Corpus of Biographical Texts',
 'Codon usage',
 'Intelligent Media Accelerometer and Gyroscope (IM-AccGyro) Dataset',
 'Myocardial infarction complications',
 'Hungarian Chickenpox Cases',
 'Simulated data for survival modelling',
 'Student Performance on an entrance examination',
 'Chemical Composition of Ceramic Samples',
 'Labeled Text Forum Threads Dataset',
 'Stock keeping units',
 'BLE RSSI dataset for Indoor localization',
 'Basketball dataset',
 'GitHub MUSAE',
 'Anticancer peptides',
 'Monolithic Columns in Troad and Mysia Region',
 'Gender by Name',
 'Iranian Churn Dataset',
 'Unmanned Aerial Vehicle (UAV) Intrusion Detection',
 'Shoulder Implant Manufacture Classification',
 'LastFM Asia Social Network',
 'Wheat kernels',
 'Productivity Prediction of Garment Employees',
 'Multi-view Brain Networks',
 'LastFM Asia Social Network',
 'Wisesight Sentiment Corpus',
 'AI4I 2020 Predictive Maintenance Dataset',
 'Dry Bean Dataset',
 'in-vehicle coupon recommendation',
 'Gait Classification',
 'Wikipedia Math Essentials',
 'Wikipedia Math Essentials',
 'Synchronous Machine Data Set',
 'Average Localization Error (ALE) in sensor node localization process in WSNs',
 '9mers from cullpdb',
 'TamilSentiMix',
 'Accelerometer',
 'Synchronous Machine Data Set',
 'Pedal Me Bicycle Deliveries',
 'Turkish Headlines Dataset',
 'Secondary Mushroom Dataset',
 'Power consumption of Tetouan city',
 'Raisin Dataset',
 'Steel Industry Energy Consumption Dataset',
 'Gender Gap in Spanish WP',
 'Non verbal tourists data',
 'Roman Urdu Sentiment Analysis Dataset (RUSAD)',
 'TUANDROMD ( Tezpur University Android Malware Dataset)',
 'Higher Education Students Performance Evaluation Dataset',
 'Risk Factor prediction of Chronic Kidney Disease',
 'Lab Test',
 'Shoulder Implant Manufacture Classification',
 'Rocket League Skillshots Data Set',
 'Sepsis survival minimal clinical records',
 'Water Quality Prediction',
 'Traffic Flow Forecasting',
 'sentiment analysis in Saudi Arabia about distance education during Covid-19',
 'Kain Tradisional Sambas',

In [33]:
Data_Type=[]

Data_Type_tags=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[2]/td[2]/p")
#Data_Type_tags=driver.find_elements(By.XPATH,"//p[@class='normal']//body//table[2]//tbody//tr//td[2]//table[2]//tbody//tr[2]//td[2]//p")
#Data_Type_tags=driver.find_elements(By.XPATH,"//p[@class='normal']//body//table[2]//tbody//tr//td[2]//table[2]//tbody//tr[2]//td[2]//p")
for i in Data_Type_tags:
    #time.sleep(5)
    try:
        Data_Type.append(i.text)
    except NoSuchElementException :
        Data_Type.append('Not present')

In [34]:
Data_Type

['Multivariate ']